services:
  - type: web
    name: cardio-ml-project
    env: python
    plan: free
    buildCommand: pip install -r CardioProjectFrontend/requirements.txt
    startCommand: gunicorn CardioProjectFrontend.app:app
    rootDir: .
